#!/usr/bin/env python3

import sys
import os

# Add the current directory to the path
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, current_dir)

from slab_buddy_info.main import main

if __name__ == "__main__":
    main()
